from django.urls import path

from .compat_views import (
    CompatAuthLoginView,
    CompatAuthLogoutView,
    CompatAuthMeView,
    CompatCarDetailView,
    CompatCarSearchView,
    CompatCarsView,
    CompatCurrentUserSessionsView,
    CompatCustomerPortalApprovalView,
    CompatCustomerPortalSessionView,
    CompatDocumentsByIdsView,
    CompatHistoryView,
    CompatInsuranceProviderDetailView,
    CompatInsuranceProvidersView,
    CompatInvoiceDetailView,
    CompatInvoiceNextNumberView,
    CompatInvoicesByJobCardView,
    CompatInvoicesView,
    CompatJobCardDetailView,
    CompatJobCardSendApprovalView,
    CompatJobCardsView,
    CompatLabourDetailView,
    CompatLabourView,
    CompatMechanicJobCardCompleteView,
    CompatMechanicJobCardOpenView,
    CompatMechanicJobCardProgressView,
    CompatMechanicJobCardsView,
    CompatPartsDetailView,
    CompatPartsView,
    CompatPostDeliveryInspectionView,
    CompatTempCarDetailView,
    CompatTempCarsView,
    CompatUserDetailView,
    CompatUserListView,
    CompatVehicleModelsView,
    CompatWalletAddCreditView,
    CompatWalletDetailView,
    CompatWalletsView,
    CompatTodayOperationsView,
)

urlpatterns = [
    path("auth/login/", CompatAuthLoginView.as_view(), name="compat-auth-login"),
    path("auth/logout/", CompatAuthLogoutView.as_view(), name="compat-auth-logout"),
    path("auth/me/", CompatAuthMeView.as_view(), name="compat-auth-me"),
    path(
        "auth/sessions/",
        CompatCurrentUserSessionsView.as_view(),
        name="compat-auth-sessions",
    ),
    path("history/", CompatHistoryView.as_view(), name="compat-history"),
    path(
        "documents/by-ids/",
        CompatDocumentsByIdsView.as_view(),
        name="compat-documents-by-ids",
    ),
    path("users/", CompatUserListView.as_view(), name="compat-users"),
    path("users/<int:pk>/", CompatUserDetailView.as_view(), name="compat-user-detail"),
    path("cars/", CompatCarsView.as_view(), name="compat-cars"),
    path("cars/search/", CompatCarSearchView.as_view(), name="compat-cars-search"),
    path("cars/<str:pk>/", CompatCarDetailView.as_view(), name="compat-car-detail"),
    path("temp-cars/", CompatTempCarsView.as_view(), name="compat-temp-cars"),
    path(
        "temp-cars/<str:pk>/",
        CompatTempCarDetailView.as_view(),
        name="compat-temp-car-detail",
    ),
    path("jobcards/", CompatJobCardsView.as_view(), name="compat-jobcards"),
    path(
        "jobcards/<uuid:pk>/",
        CompatJobCardDetailView.as_view(),
        name="compat-jobcard-detail",
    ),
    path(
        "jobcards/<uuid:pk>/send-approval/",
        CompatJobCardSendApprovalView.as_view(),
        name="compat-jobcard-send-approval",
    ),
    path(
        "jobcards/<uuid:pk>/post-delivery-inspection/",
        CompatPostDeliveryInspectionView.as_view(),
        name="compat-jobcard-post-delivery-inspection",
    ),
    path(
        "portal/",
        CompatCustomerPortalSessionView.as_view(),
        name="compat-customer-portal-session",
    ),
    path(
        "portal/approvals/<uuid:approval_id>/",
        CompatCustomerPortalApprovalView.as_view(),
        name="compat-customer-portal-approval",
    ),
    path(
        "mechanic/jobcards/",
        CompatMechanicJobCardsView.as_view(),
        name="compat-mechanic-jobcards",
    ),
    path(
        "mechanic/jobcards/<uuid:pk>/open/",
        CompatMechanicJobCardOpenView.as_view(),
        name="compat-mechanic-jobcard-open",
    ),
    path(
        "mechanic/jobcards/<uuid:pk>/progress/",
        CompatMechanicJobCardProgressView.as_view(),
        name="compat-mechanic-jobcard-progress",
    ),
    path(
        "mechanic/jobcards/<uuid:pk>/complete/",
        CompatMechanicJobCardCompleteView.as_view(),
        name="compat-mechanic-jobcard-complete",
    ),
    path("parts/", CompatPartsView.as_view(), name="compat-parts"),
    path("parts/<str:pk>/", CompatPartsDetailView.as_view(), name="compat-part-detail"),
    path("labour/", CompatLabourView.as_view(), name="compat-labour"),
    path(
        "labour/<str:pk>/",
        CompatLabourDetailView.as_view(),
        name="compat-labour-detail",
    ),
    path("wallets/", CompatWalletsView.as_view(), name="compat-wallets"),
    path(
        "wallets/<int:car_id>/",
        CompatWalletDetailView.as_view(),
        name="compat-wallet-detail",
    ),
    path(
        "wallets/<int:car_id>/credits/",
        CompatWalletAddCreditView.as_view(),
        name="compat-wallet-add-credit",
    ),
    path("invoices/", CompatInvoicesView.as_view(), name="compat-invoices"),
    path(
        "invoices/<str:pk>/",
        CompatInvoiceDetailView.as_view(),
        name="compat-invoice-detail",
    ),
    path(
        "jobcards/<uuid:jobcard_id>/invoices/next-number/",
        CompatInvoiceNextNumberView.as_view(),
        name="compat-invoice-next-number",
    ),
    path(
        "jobcards/<uuid:jobcard_id>/invoices/",
        CompatInvoicesByJobCardView.as_view(),
        name="compat-invoices-by-jobcard",
    ),
    path(
        "vehicle-models/",
        CompatVehicleModelsView.as_view(),
        name="compat-vehicle-models",
    ),
    path(
        "policy-providers/",
        CompatInsuranceProvidersView.as_view(),
        name="compat-policy-providers",
    ),
    path(
        "policy-providers/<uuid:pk>/",
        CompatInsuranceProviderDetailView.as_view(),
        name="compat-policy-provider-detail",
    ),
    path(
        "insurance-providers/",
        CompatInsuranceProvidersView.as_view(),
        name="compat-insurance-providers",
    ),
    path(
        "insurance-providers/<uuid:pk>/",
        CompatInsuranceProviderDetailView.as_view(),
        name="compat-insurance-provider-detail",
    ),
    path(
        "dashboard/today/",
        CompatTodayOperationsView.as_view(),
        name="compat-dashboard-today",
    ),
]
