from django.urls import path

from .compat_views import (
    CompatAuthLoginView,
    CompatAuthLogoutView,
    CompatAuthMeView,
    CompatCarsView,
    CompatCarDetailView,
    CompatCarSearchView,
    CompatDocumentsByIdsView,
    CompatCurrentUserSessionsView,
    CompatHistoryView,
    CompatInvoicesByJobCardView,
    CompatInvoiceDetailView,
    CompatInvoiceNextNumberView,
    CompatInvoicesView,
    CompatJobCardDetailView,
    CompatJobCardsView,
    CompatLabourView,
    CompatLabourDetailView,
    CompatPolicyProvidersView,
    CompatPartsDetailView,
    CompatTempCarDetailView,
    CompatTempCarsView,
    CompatUserListView,
    CompatVehicleModelsView,
    CompatPartsView,
)

urlpatterns = [
    path("auth/login/", CompatAuthLoginView.as_view(), name="compat-auth-login"),
    path("auth/logout/", CompatAuthLogoutView.as_view(), name="compat-auth-logout"),
    path("auth/me/", CompatAuthMeView.as_view(), name="compat-auth-me"),
    path("auth/sessions/", CompatCurrentUserSessionsView.as_view(), name="compat-auth-sessions"),
    path("history/", CompatHistoryView.as_view(), name="compat-history"),
    path("documents/by-ids/", CompatDocumentsByIdsView.as_view(), name="compat-documents-by-ids"),
    path("users/", CompatUserListView.as_view(), name="compat-users"),
    path("cars/", CompatCarsView.as_view(), name="compat-cars"),
    path("cars/search/", CompatCarSearchView.as_view(), name="compat-cars-search"),
    path("cars/<str:pk>/", CompatCarDetailView.as_view(), name="compat-car-detail"),
    path("temp-cars/", CompatTempCarsView.as_view(), name="compat-temp-cars"),
    path("temp-cars/<str:pk>/", CompatTempCarDetailView.as_view(), name="compat-temp-car-detail"),
    path("jobcards/", CompatJobCardsView.as_view(), name="compat-jobcards"),
    path("jobcards/<uuid:pk>/", CompatJobCardDetailView.as_view(), name="compat-jobcard-detail"),
    path("parts/", CompatPartsView.as_view(), name="compat-parts"),
    path("parts/<str:pk>/", CompatPartsDetailView.as_view(), name="compat-part-detail"),
    path("labour/", CompatLabourView.as_view(), name="compat-labour"),
    path("labour/<str:pk>/", CompatLabourDetailView.as_view(), name="compat-labour-detail"),
    path("invoices/", CompatInvoicesView.as_view(), name="compat-invoices"),
    path("invoices/<str:pk>/", CompatInvoiceDetailView.as_view(), name="compat-invoice-detail"),
    path("jobcards/<uuid:jobcard_id>/invoices/next-number/", CompatInvoiceNextNumberView.as_view(), name="compat-invoice-next-number"),
    path("jobcards/<uuid:jobcard_id>/invoices/", CompatInvoicesByJobCardView.as_view(), name="compat-invoices-by-jobcard"),
    path("vehicle-models/", CompatVehicleModelsView.as_view(), name="compat-vehicle-models"),
    path("policy-providers/", CompatPolicyProvidersView.as_view(), name="compat-policy-providers"),
]
