# Generated by Django 4.2.30 on 2026-06-29 02:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment', 'Adjustment')], default='sale', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_delta', models.IntegerField()),
                ('before_quantity', models.PositiveIntegerField()),
                ('after_quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('itemCode', models.CharField(blank=True, max_length=50, null=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('itemLocation', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('msp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('vendorCode', models.CharField(blank=True, max_length=50, null=True)),
                ('vendorName', models.CharField(blank=True, max_length=100, null=True)),
                ('purchasePrice', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('purchaseLocation', models.CharField(blank=True, max_length=500, null=True)),
                ('purchaseOrderDate', models.DateField(blank=True, null=True)),
                ('purchaseOrderId', models.CharField(blank=True, max_length=50, null=True)),
                ('warrantyPeriod', models.CharField(blank=True, max_length=50, null=True)),
                ('lastUpdatedDate', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
