# Generated by Django 4.2.30 on 2026-05-21 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_invoice_inventory_consumed_at_and_more'),
        ('jobcards', '0002_jobcard_inventory_consumed_at_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('sale', 'Sale'), ('adjustment', 'Adjustment')], default='sale', max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_delta', models.IntegerField()),
                ('before_quantity', models.PositiveIntegerField()),
                ('after_quantity', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='jobcards.currentpart')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='billing.invoice')),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='jobcards.jobcard')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_movements', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
