# Generated by Django 4.2.29 on 2026-04-13 07:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insurer', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('gst', models.CharField(blank=True, max_length=50, verbose_name='GST Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labour',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labour_name', models.CharField(max_length=255)),
                ('labour_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('hsn', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehilceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=255)),
                ('models', models.JSONField(blank=True, default=list, help_text="A list of model names, e.g. ['A4','Q5','TT']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
