# Generated by Django 4.2.30 on 2026-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour',
            name='labour_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
