# Generated by Django 4.2.29 on 2026-04-13 07:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('bds', 'BDS'), ('src', 'SRC')], max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_series', models.CharField(choices=[('bds', 'BDS'), ('src', 'SRC')], max_length=10)),
                ('invoice_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_code', models.CharField(blank=True, max_length=50)),
                ('car_number', models.CharField(blank=True, max_length=50)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_insurance_invoice', models.BooleanField(default=False)),
                ('invoice_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='jobcards.jobcard')),
            ],
            options={
                'ordering': ['invoice_series', 'invoice_type', 'invoice_number'],
                'unique_together': {('invoice_series', 'invoice_type', 'invoice_number')},
            },
        ),
    ]
