# Generated by Django 4.2.30 on 2026-06-29 02:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_series', models.CharField(choices=[('bds', 'BDS'), ('src', 'SRC')], max_length=10)),
                ('invoice_type', models.CharField(max_length=50)),
                ('category', models.CharField(blank=True, default='', max_length=20)),
                ('invoice_number', models.PositiveIntegerField()),
                ('invoice_code', models.CharField(blank=True, max_length=50)),
                ('car_number', models.CharField(blank=True, max_length=50)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_insurance_invoice', models.BooleanField(default=False)),
                ('inventory_consumed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('wallet_credit_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('apply_gst', models.BooleanField(default=True)),
                ('invoice_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['invoice_series', 'invoice_type', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('bds', 'BDS'), ('src', 'SRC')], max_length=10, unique=True)),
                ('last_number', models.PositiveIntegerField(default=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField()),
                ('type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='billing.customerwallet')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
