# Generated by Django 4.2.30 on 2026-06-29 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicle_management', '0001_initial'),
        ('jobcards', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='jobcards.jobcard'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='wallet_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='billing.wallettransaction'),
        ),
        migrations.AddField(
            model_name='customerwallet',
            name='car',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallet', to='vehicle_management.car'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('invoice_series', 'invoice_type', 'invoice_number')},
        ),
    ]
