# Generated by Django 4.2.30 on 2026-05-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='inventory_consumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoicecounter',
            name='last_number',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
