# Generated by Django 4.2.30 on 2026-07-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_series',
            field=models.CharField(choices=[('BDS', 'BDS'), ('SER', 'SER')], max_length=10),
        ),
        migrations.AlterField(
            model_name='invoicecounter',
            name='series',
            field=models.CharField(choices=[('BDS', 'BDS'), ('SER', 'SER')], max_length=10, unique=True),
        ),
    ]
