# Generated by Django 4.2.30 on 2026-04-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedasset',
            name='file',
        ),
        migrations.AddField(
            model_name='uploadedasset',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
