# Generated by Django 4.2.30 on 2026-07-07 21:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedJobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_card_snapshot', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('raw_details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='car_id',
            field=models.CharField(help_text='External/business-facing jobcard identifier', max_length=100),
        ),
    ]
