# Generated by Django 4.2.30 on 2026-06-12 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0002_jobcard_inventory_consumed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='assigned_technician_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='delivery_inspection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='insurance_policy_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='labour_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
