# Generated by Django 4.2.30 on 2026-10-08 06:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobcards', '0004_telecrmleadsync_period_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='caller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caller_job_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
