# Generated by Django 4.2.30 on 2026-06-13 08:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0005_jobcard_suggested_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='advisor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='approved_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='recommended_labour',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='recommended_parts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='workflow_status',
            field=models.CharField(choices=[('JOB_CARD_CREATED', 'Job Card Created'), ('WAITING_CUSTOMER_APPROVAL', 'Waiting Customer Approval'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_PARTIALLY_APPROVED', 'Customer Partially Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('POST_DELIVERY_INSPECTION_PENDING', 'Post Delivery Inspection Pending')], default='JOB_CARD_CREATED', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomerApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PARTIALLY_APPROVED', 'Partially Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('link_created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_approvals', to='jobcards.jobcard')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(choices=[('PART', 'Part'), ('LABOUR', 'Labour')], max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image', models.URLField(blank=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='jobcards.customerapproval')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
