# Generated by Django 4.2.30 on 2026-06-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0006_jobcard_advisor_notes_jobcard_approved_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='mechanic_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='mechanic_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='workflow_status',
            field=models.CharField(choices=[('JOB_CARD_CREATED', 'Job Card Created'), ('WAITING_CUSTOMER_APPROVAL', 'Waiting Customer Approval'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_PARTIALLY_APPROVED', 'Customer Partially Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('MECHANIC_IN_PROGRESS', 'Mechanic In Progress'), ('MECHANIC_COMPLETED', 'Mechanic Completed'), ('POST_DELIVERY_INSPECTION_PENDING', 'Post Delivery Inspection Pending')], default='JOB_CARD_CREATED', max_length=50),
        ),
    ]
