# Generated by Django 4.2.30 on 2026-06-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0007_jobcard_mechanic_checklist_jobcard_mechanic_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='post_delivery_checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='post_delivery_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='post_delivery_completed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='post_delivery_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='workflow_status',
            field=models.CharField(choices=[('JOB_CARD_CREATED', 'Job Card Created'), ('WAITING_CUSTOMER_APPROVAL', 'Waiting Customer Approval'), ('CUSTOMER_APPROVED', 'Customer Approved'), ('CUSTOMER_PARTIALLY_APPROVED', 'Customer Partially Approved'), ('CUSTOMER_REJECTED', 'Customer Rejected'), ('MECHANIC_IN_PROGRESS', 'Mechanic In Progress'), ('MECHANIC_COMPLETED', 'Mechanic Completed'), ('POST_DELIVERY_INSPECTION_PENDING', 'Post Delivery Inspection Pending'), ('POST_DELIVERY_COMPLETED', 'Post Delivery Inspection Completed'), ('VEHICLE_COLLECTED', 'Vehicle Collected')], default='JOB_CARD_CREATED', max_length=50),
        ),
    ]
