# Generated by Django 4.2.30 on 2026-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0008_jobcard_post_delivery_checklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='accessories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
