# Generated by Django 4.2.30 on 2026-06-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0009_jobcard_accessories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcard',
            name='accessories',
        ),
    ]
