# Generated by Django 4.2.30 on 2026-06-17 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcards', '0010_remove_jobcard_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='accessories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
