# Generated by Django 4.2.30 on 2026-06-25 09:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobcards", "0011_jobcard_accessories"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobcard",
            name="required_date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
